repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format (uv)
        entry: uv run ruff format .
        language: system
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check and fix (uv)
        entry: uv run ruff check . --fix
        language: system
        types_or: [python, pyi]

      - id: pytest
        name: pytest (uv)
        entry: env PYTHONPATH=./src uv run pytest -vv --capture=no tests
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: pyright (uv)
        entry: uv run pyright
        language: system
        pass_filenames: false
